version: '2'
services:
  jhipstersampleapplication2-app:
    image: jhipstersampleapplication2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplication2-mysql:3306/jhipstersampleapplication2?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhipstersampleapplication2-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhipstersampleapplication2-elasticsearch:9200
    ports:
      - 8080:8080
  jhipstersampleapplication2-mysql:
    extends:
      file: mysql.yml
      service: jhipstersampleapplication2-mysql
  jhipstersampleapplication2-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhipstersampleapplication2-elasticsearch
